### ISSUE TITLE
Novo layout

### ISSUE THREAD

**Issue by gabrielmzl** [gamersclub-booster/gamersclub-booster.github.io#1]
![Screenshot_1](https://user-images.githubusercontent.com/61896505/150917839-ad8ba837-a089-4e88-b386-116bf32d35c7.png)
[Gamersclub Booster.zip](https://github.com/gamersclub-booster/gamersclub-booster.github.io/files/7930866/Gamersclub.Booster.zip)

**Comment by crashzk** [comment]
@gabrielmzl sugestão, poderia colocar algumas prints da extensão, como ela funciona na plataforma e etc.

Algo parecido com o que tem aqui: https://github.com/gamersclub-booster/gamersclub-booster/blob/development/README.md

**Comment by jorgebrunetto** [comment]
@gabrielmzl Feito, atualizamos e usamos seu exemplo, já coloquei tambem como contribuidor
